"""added name to Event

Revision ID: 0991da35cb07
Revises: b913ca1282b2
Create Date: 2023-10-18 12:24:23.658343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0991da35cb07'
down_revision = 'b913ca1282b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
