"""added pics to event

Revision ID: 1893dff556fd
Revises: 0991da35cb07
Create Date: 2023-10-19 09:17:54.818496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1893dff556fd'
down_revision = '0991da35cb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
